version: '2'

services:
  n3uron:
    image: n3uronhub/n3uron:v1.21.7
    ports:
      - 80:8003   # HTTP WebUI for balena's Public Device URL feature
      - 8003:8003 # HTTP WebUI
      - 8443:8443 # HTTPS WebUI
      - 8004:8004 # HTTP WebVision
      - 8444:8444 # HTTPS WebVision
      - 3001:3001 # Inbound Links
    environment:
      - HOSTNAME=balena-historian
    volumes:
      - n3_config:/opt/n3uron/config
      - n3_data:/opt/n3uron/data
      - n3_licenses:/opt/n3uron/licenses
      - n3_log:/opt/n3uron/log
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    restart: always

  mongo:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    restart: always

  mqtt:
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883
    restart: always

volumes:
  n3_config:
  n3_data:
  n3_licenses:
  n3_log:
  mongo_data:
